### ISSUE TITLE
v2 Deprecation

### ISSUE THREAD

**Issue by Artucuno** [torpyorg/torpy#31] opened 2021-06-08 12:16 UTC
When will V3 support be available, Tor has updated the start page saying that V2 will be gone soon.

**Comment by jbrown299** [comment] 2021-09-17 05:43
Duplicate of https://github.com/torpyorg/torpy/issues/15

**Closed as completed by jbrown299** 2021-09-17 05:43 UTC

**Comment by SafwanLjd** [comment] 2026-07-18 19:08
Late answer to the v3 question: it lives in torquests now. Speaks the Tor protocol in Python, does v3 hidden services, and you call it the way you would call requests. https://github.com/SafwanLjd/torquests
